[package]
name = "dhcpm"
version = "0.1.0"
edition = "2021"
authors = ["Evan Cameron <cameron.evan@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dhcproto = { git = "https://github.com/bluecatengineering/dhcproto" }
anyhow = "1.0"
argh = "0.1.7"
crossbeam-channel = "0.5.1"
ctrlc = "3.1"
mac_address = "1.1.1"
tracing = "0.1"
tracing-subscriber = "0.2"
rand = "0.8"
hex = "0.4"
rhai = { version = "1.5.0", optional = true }
# rhai-rand = { version = "0.1", optional = true }

[features]
default = []
script = ["rhai"]